/* Auto-generated for CAT Prep With Ajeet Sir. Upload this at repo root. */
window.CAT_TESTS = [
  {
    "title": "Area wise Logical Reasoning Test 1",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -1.html",
    "original": "Area wise  Logical Reasoning Test -1.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area wise Logical Reasoning Test 2",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -2.html",
    "original": "Area wise  Logical Reasoning Test -2.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area wise Logical Reasoning Test 3",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -3.html",
    "original": "Area wise  Logical Reasoning Test -3.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area wise Logical Reasoning Test 4",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -4.html",
    "original": "Area wise  Logical Reasoning Test -4.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area wise Logical Reasoning Test 5",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -5.html",
    "original": "Area wise  Logical Reasoning Test -5.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area wise Logical Reasoning Test 6",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR/Area wise  Logical Reasoning Test -6.html",
    "original": "Area wise  Logical Reasoning Test -6.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Arithmetic Test 1",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Arithmetic/Area Wise - Arithmetic Test  -1.html",
    "original": "Area Wise - Arithmetic Test  -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Arithmetic Test 2",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Arithmetic/Area Wise - Arithmetic Test  -2.html",
    "original": "Area Wise - Arithmetic Test  -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Arithmetic Test 3",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Arithmetic/Area Wise - Arithmetic Test  -3.html",
    "original": "Area Wise - Arithmetic Test  -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Number System test 1",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Number System/Area Wise  Number System  test -1.html",
    "original": "Area Wise  Number System  test -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Number System test 2",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Number System/Area Wise  Number System  test -2.html",
    "original": "Area Wise  Number System  test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Number System test 3",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Number System/Area Wise  Number System  test -3.html",
    "original": "Area Wise  Number System  test -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Area Wise Number System test 4",
    "file": "CAT PREP with Ajeet sir/Area Wise Test/QA/Number System/Area Wise  Number System  test -4.html",
    "original": "Area Wise  Number System  test -4.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Area Wise Test",
    "minutes": 60,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 1",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -1.html",
    "original": "LRDI Set -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 10",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -10.html",
    "original": "LRDI Set -10.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 11",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -11.html",
    "original": "LRDI Set -11.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 12",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -12.html",
    "original": "LRDI Set -12.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 13",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -13.html",
    "original": "LRDI Set -13.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 14",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -14.html",
    "original": "LRDI Set -14.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 15",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -15.html",
    "original": "LRDI Set -15.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 16",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -16.html",
    "original": "LRDI Set -16.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 17",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -17.html",
    "original": "LRDI Set -17.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 2",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -2.html",
    "original": "LRDI Set -2.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 3",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -3.html",
    "original": "LRDI Set -3.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 4",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -4.html",
    "original": "LRDI Set -4.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 5",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -5.html",
    "original": "LRDI Set -5.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 6",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -6.html",
    "original": "LRDI Set -6.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 7",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -7.html",
    "original": "LRDI Set -7.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 8",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -8.html",
    "original": "LRDI Set -8.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "LRDI Set 9",
    "file": "CAT PREP with Ajeet sir/Daily LRDI/LRDI Set -9.html",
    "original": "LRDI Set -9.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Topic Test Arithmetic Percentage PYQ",
    "file": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA/Arithmetic/1.Percentage/Topic Test - Arithmetic - Percentage PYQ.html",
    "original": "Topic Test - Arithmetic - Percentage PYQ.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "PYQ QA Ratio Proportion Variation PYQ",
    "file": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA/Arithmetic/2.Ratio Proportion/PYQ - QA - Ratio Proportion Variation PYQ.html",
    "original": "PYQ - QA - Ratio Proportion Variation PYQ.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI Bar Graph Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Bar Graph/DI - Bar Graph - Test -1.html",
    "original": "DI - Bar Graph - Test -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI Bar Graph Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Bar Graph/DI - Bar Graph - Test -2.html",
    "original": "DI - Bar Graph - Test -2.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI Line Graph 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Line Graph/DI - Line Graph -2.html",
    "original": "DI - Line Graph -2.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI LINE GRAPH 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Line Graph/DI LINE GRAPH -1.html",
    "original": "DI LINE GRAPH -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DILR Network & 3D diagram 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Network & 3D Graph/DILR - Network & 3D diagram -1.html",
    "original": "DILR - Network & 3D diagram -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI PIE CHART 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Pie Chart/DI PIE CHART -1.html",
    "original": "DI PIE CHART -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI PIE CHART 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Pie Chart/DI PIE CHART -2.html",
    "original": "DI PIE CHART -2.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI Table Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Table/DI - Table - Test -1.html",
    "original": "DI - Table - Test -1.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DI Table Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Table/DI - Table - Test -2.html",
    "original": "DI - Table - Test -2.html",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DILR Games & Tournaments 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Games & Tournaments/DILR - Games & Tournaments -1.html",
    "original": "DILR - Games & Tournaments -1.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "DILR Games & Tournaments 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Games & Tournaments/DILR - Games & Tournaments -2.html",
    "original": "DILR - Games & Tournaments -2.html",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "minutes": 25,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Linear Equation Basics 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Linear Equation/Linear Equation Basics -1.html",
    "original": "Linear Equation Basics -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Linear Equation Basics 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Linear Equation/Linear Equation Basics -2.html",
    "original": "Linear Equation Basics -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Linear Equation Basics 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Linear Equation/Linear Equation Basics -3.html",
    "original": "Linear Equation Basics -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-1.html",
    "original": "Percentage Test-1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-2.html",
    "original": "Percentage Test-2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-3.html",
    "original": "Percentage Test-3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 4",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-4.html",
    "original": "Percentage Test-4.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 5",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-5.html",
    "original": "Percentage Test-5.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 6",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-6.html",
    "original": "Percentage Test-6.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 7",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-7.html",
    "original": "Percentage Test-7.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Percentage Test 8",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage/Percentage Test-8.html",
    "original": "Percentage Test-8.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -1.html",
    "original": "Ratio Proportion Variation Partnership  Test -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 10",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -10.html",
    "original": "Ratio Proportion Variation Partnership  Test -10.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 11",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -11.html",
    "original": "Ratio Proportion Variation Partnership  Test -11.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 12",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -12.html",
    "original": "Ratio Proportion Variation Partnership  Test -12.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 13",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -13.html",
    "original": "Ratio Proportion Variation Partnership  Test -13.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -2.html",
    "original": "Ratio Proportion Variation Partnership  Test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -3.html",
    "original": "Ratio Proportion Variation Partnership  Test -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 4",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -4.html",
    "original": "Ratio Proportion Variation Partnership  Test -4.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 5",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -5.html",
    "original": "Ratio Proportion Variation Partnership  Test -5.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 6",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -6.html",
    "original": "Ratio Proportion Variation Partnership  Test -6.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 7",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -7.html",
    "original": "Ratio Proportion Variation Partnership  Test -7.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 8",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -8.html",
    "original": "Ratio Proportion Variation Partnership  Test -8.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Ratio Proportion Variation Partnership Test 9",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion/Ratio Proportion Variation Partnership  Test -9.html",
    "original": "Ratio Proportion Variation Partnership  Test -9.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Profit Loss Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss/Profit Loss  Test -2.html",
    "original": "Profit Loss  Test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Profit Loss Test 5",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss/Profit Loss  Test -5.html",
    "original": "Profit Loss  Test -5.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Profit Loss Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss/Profit Loss Test -1.html",
    "original": "Profit Loss Test -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Profit Loss Test 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss/Profit Loss Test -3.html",
    "original": "Profit Loss Test -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Profit Loss Test 4",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss/Profit Loss Test -4.html",
    "original": "Profit Loss Test -4.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "SI & CI Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/4.SI & CI/SI & CI Test -1.html",
    "original": "SI & CI Test -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "SI & CI Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/4.SI & CI/SI & CI Test -2.html",
    "original": "SI & CI Test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Average Test 1",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average/Average Test -1.html",
    "original": "Average Test -1.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Average Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average/Average Test -2.html",
    "original": "Average Test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Average Test 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average/Average Test -3.html",
    "original": "Average Test -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Average Test 4",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average/Average Test -4.html",
    "original": "Average Test -4.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Average Test 5",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average/Average Test 5.html",
    "original": "Average Test 5.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Number System Properties of Numbers Test 2 (2)",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/1.Properties Of Number/Number System - Properties of Numbers  Test -2 (2).html",
    "original": "Number System - Properties of Numbers  Test -2 (2).html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "Number System Properties of Numbers Test 2",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/1.Properties Of Number/Number System - Properties of Numbers  Test -2.html",
    "original": "Number System - Properties of Numbers  Test -2.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  },
  {
    "title": "number system properties of numbers Test 3",
    "file": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/1.Properties Of Number/number-system-properties-of-numbers Test -3.html",
    "original": "number-system-properties-of-numbers Test -3.html",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "minutes": 40,
    "questions": null,
    "status": "Available"
  }
];

window.CAT_FOLDERS = [
  {
    "title": "Area Wise Test",
    "path": "CAT PREP with Ajeet sir/Area Wise Test",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "testsCount": 13,
    "status": "Ready"
  },
  {
    "title": "LRDI",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/LRDI",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "testsCount": 6,
    "status": "Ready"
  },
  {
    "title": "DI",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/DI",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Area Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "LR",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/LRDI/LR",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Area Wise Test",
    "testsCount": 6,
    "status": "Ready"
  },
  {
    "title": "QA",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/QA",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "testsCount": 7,
    "status": "Ready"
  },
  {
    "title": "Algebra",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/QA/Algebra",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Area Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Arithmetic",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/QA/Arithmetic",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Area Wise Test",
    "testsCount": 3,
    "status": "Ready"
  },
  {
    "title": "Geometry",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/QA/Geometry",
    "area": "Quant",
    "subject": "QA",
    "topic": "Geometry",
    "qaTopic": "geometry",
    "type": "Area Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Number System",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/QA/Number System",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Area Wise Test",
    "testsCount": 4,
    "status": "Ready"
  },
  {
    "title": "RC",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/VARC/RC",
    "area": "VARC",
    "subject": "RC",
    "topic": "Reading Comprehension",
    "qaTopic": "",
    "type": "Area Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "VA - VR",
    "path": "CAT PREP with Ajeet sir/Area Wise Test/VARC/VA-VR",
    "area": "VARC",
    "subject": "VA-VR",
    "topic": "VA-VR",
    "qaTopic": "",
    "type": "Area Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Daily LRDI",
    "path": "CAT PREP with Ajeet sir/Daily LRDI",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 17,
    "status": "Ready"
  },
  {
    "title": "CAT Full Mocks",
    "path": "CAT PREP with Ajeet sir/Full Length Test/CAT Full Mocks",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Full Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "PYQ",
    "path": "CAT PREP with Ajeet sir/PYQ",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Topic Wise",
    "path": "CAT PREP with Ajeet sir/PYQ/Topic Wise",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "QA",
    "path": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Arithmetic",
    "path": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA/Arithmetic",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Percentage",
    "path": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA/Arithmetic/1.Percentage",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 1,
    "status": "Ready"
  },
  {
    "title": "Ratio Proportion",
    "path": "CAT PREP with Ajeet sir/PYQ/Topic Wise/QA/Arithmetic/2.Ratio Proportion",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 1,
    "status": "Ready"
  },
  {
    "title": "LRDI",
    "path": "CAT PREP with Ajeet sir/Sectional Test/LRDI",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Sectional Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "QA",
    "path": "CAT PREP with Ajeet sir/Sectional Test/QA",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Sectional Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "VARC",
    "path": "CAT PREP with Ajeet sir/Sectional Test/VARC",
    "area": "VARC",
    "subject": "VA-VR",
    "topic": "VA-VR",
    "qaTopic": "",
    "type": "Sectional Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Topic Test",
    "path": "CAT PREP with Ajeet sir/Topic Test",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 50,
    "status": "Ready"
  },
  {
    "title": "LRDI",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 11,
    "status": "Ready"
  },
  {
    "title": "DI",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 9,
    "status": "Ready"
  },
  {
    "title": "Bar Graph",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Bar Graph",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Caselet",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Caselet",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Line Graph",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Line Graph",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Network & 3D Graph",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Network & 3D Graph",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 1,
    "status": "Ready"
  },
  {
    "title": "Pie Chart",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Pie Chart",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Table",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/DI/Table",
    "area": "LRDI",
    "subject": "DI",
    "topic": "Data Interpretation",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "LR",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Arrangements",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Arrangements",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Games & Tournaments",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Games & Tournaments",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Routes & Networks",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Routes & Networks",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Selection & Distribution",
    "path": "CAT PREP with Ajeet sir/Topic Test/LRDI/LR/Selection & Distribution",
    "area": "LRDI",
    "subject": "LR",
    "topic": "Logical Reasoning",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "QA",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 39,
    "status": "Ready"
  },
  {
    "title": "Algebra",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "testsCount": 3,
    "status": "Ready"
  },
  {
    "title": "Functions",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Functions",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Inequalities",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Inequalities",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Linear Equation",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Linear Equation",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "testsCount": 3,
    "status": "Ready"
  },
  {
    "title": "Quadratic Equation",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Algebra/Quadratic Equation",
    "area": "Quant",
    "subject": "QA",
    "topic": "Algebra",
    "qaTopic": "algebra",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Arithmetic",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 33,
    "status": "Ready"
  },
  {
    "title": "Percentage",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/1.Percentage",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 8,
    "status": "Ready"
  },
  {
    "title": "Ratio Proportion",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/2.Ratio Proportion",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 13,
    "status": "Ready"
  },
  {
    "title": "Profit & Loss",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/3.Profit & Loss",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 5,
    "status": "Ready"
  },
  {
    "title": "SI & CI",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/4.SI & CI",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 2,
    "status": "Ready"
  },
  {
    "title": "Average",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/5. Average",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 5,
    "status": "Ready"
  },
  {
    "title": "Mixture Alligation",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/6.Mixture Alligation",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Time & Work",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/7.Time & Work",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Time Speed Distance",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Arithmetic/8.Time Speed Distance",
    "area": "Quant",
    "subject": "QA",
    "topic": "Arithmetic",
    "qaTopic": "arithmetic",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Circle",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Geometry/Circle",
    "area": "Quant",
    "subject": "QA",
    "topic": "Geometry",
    "qaTopic": "geometry",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Mensuration",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Geometry/Mensuration",
    "area": "Quant",
    "subject": "QA",
    "topic": "Geometry",
    "qaTopic": "geometry",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Triangle",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Geometry/Triangle",
    "area": "Quant",
    "subject": "QA",
    "topic": "Geometry",
    "qaTopic": "geometry",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Permutation Combination",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Modern Math/Permutation Combination",
    "area": "Quant",
    "subject": "QA",
    "topic": "Modern Math",
    "qaTopic": "modern-math",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Probability",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Modern Math/Probability",
    "area": "Quant",
    "subject": "QA",
    "topic": "Modern Math",
    "qaTopic": "modern-math",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Set Theory",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Modern Math/Set Theory",
    "area": "Quant",
    "subject": "QA",
    "topic": "Modern Math",
    "qaTopic": "modern-math",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Number System",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Number System",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "testsCount": 3,
    "status": "Ready"
  },
  {
    "title": "Properties Of Number",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/1.Properties Of Number",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "testsCount": 3,
    "status": "Ready"
  },
  {
    "title": "HCF LCM",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/2.HCF LCM",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Remainders",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/3.Remainders",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Digits",
    "path": "CAT PREP with Ajeet sir/Topic Test/QA/Number System/4.Digits",
    "area": "Quant",
    "subject": "QA",
    "topic": "Number System",
    "qaTopic": "number-system",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Reading Comprehension",
    "path": "CAT PREP with Ajeet sir/Topic Test/VARC/RC/Reading Comprehension",
    "area": "VARC",
    "subject": "RC",
    "topic": "Reading Comprehension",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Odd Sentence",
    "path": "CAT PREP with Ajeet sir/Topic Test/VARC/VA-VR/Odd Sentence",
    "area": "VARC",
    "subject": "VA-VR",
    "topic": "VA-VR",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Para Jumbles",
    "path": "CAT PREP with Ajeet sir/Topic Test/VARC/VA-VR/Para Jumbles",
    "area": "VARC",
    "subject": "VA-VR",
    "topic": "VA-VR",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  },
  {
    "title": "Summary",
    "path": "CAT PREP with Ajeet sir/Topic Test/VARC/VA-VR/Summary",
    "area": "VARC",
    "subject": "VA-VR",
    "topic": "VA-VR",
    "qaTopic": "",
    "type": "Topic Wise Test",
    "testsCount": 0,
    "status": "Upload Pending"
  }
];
